"""add retry_count and last_error to documents

Revision ID: 652a8bda6c86
Revises: aa5df5fbe94e
Create Date: 2026-07-27 16:55:46.627941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '652a8bda6c86'
down_revision: Union[str, Sequence[str], None] = 'aa5df5fbe94e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('documents', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'last_error')
    op.drop_column('documents', 'retry_count')
    # ### end Alembic commands ###
