"""add status and content_sha256 to documents

Revision ID: aa5df5fbe94e
Revises: 4a6ee2231424
Create Date: 2026-07-26 21:00:12.983491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5df5fbe94e'
down_revision: Union[str, Sequence[str], None] = '4a6ee2231424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Nota: o autogenerate também propôs derrubar chunks_document_id_idx e
    # chunks_embedding_hnsw_idx — falso positivo. Esses índices foram criados
    # manualmente na migration inicial (e30d2d2cd779), fora do modelo Python,
    # então o autogenerate não os reconhece e acha que devem sumir. Removido
    # daqui — não têm relação com esta mudança e o HNSW é crítico pro /query.
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'INDEXED', 'FAILED', name='documentstatus', native_enum=False), nullable=False))
    op.add_column('documents', sa.Column('content_sha256', sa.Text(), nullable=False))
    op.create_unique_constraint('uq_documents_content_sha256', 'documents', ['content_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_content_sha256', 'documents', type_='unique')
    op.drop_column('documents', 'content_sha256')
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
